### ISSUE TITLE
NPE: "org.jsoup.select.Elements.first()" is null

### ISSUE THREAD

**Issue by maurxce** [Inkception/discord-html-transcripts#2]
Not sure if any bug fixes will be done, but I'll post this issue regardless.
```
java.lang.NullPointerException: Cannot invoke "org.jsoup.nodes.Element.attr(String, String)" because the return value of "org.jsoup.select.Elements.first()" is null
	at me.ryzeon.transcripts.DiscordHtmlTranscripts.generateFromMessages(DiscordHtmlTranscripts.java:125)
	at md.schorn.codecontroltest.commands.impl.TicketCommand.lambda$execute$2(TicketCommand.java:106)
	at net.dv8tion.jda.api.requests.Request.lambda$onSuccess$0(Request.java:121)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
Now, I'm not familiar with jsoup, but `document.getElementsByClass("preamble__guild-icon").first()` seems odd to me, since an element with that class does exist in the html template

My code:
```java
channel.getIterableHistory().queue(messages -> {
    try (InputStream inputStream = transcripts.generateFromMessages(messages)) {
        FileUpload upload = FileUpload.fromData(inputStream, "transcript.html");
        event.replyFiles(upload).queue();
    } catch (IOException ex) {
        ex.printStackTrace();
    }
}):
```

**Comment by maurxce** [comment]
Nevermind, I had a different `template.html` in my resources folder which caused this
